ReviewPrediction/ReviewPrediction/urls.py

from django.contrib import admin
from django.urls import path,include

from . import views
urlpatterns = [
    path("", include('myapp.urls')),
    path("admin/", admin.site.urls),
]

ReviewPrediction/myapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import ExtendedAuthenticationForm

app_name = "myapp"

urlpatterns = [
    path('register/',views.register_page,name='register_page'),
    path('',auth_views.LoginView.as_view(template_name='login_page.html',authentication_form = ExtendedAuthenticationForm),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name = 'logout'),
    path('review/',views.review_form,name='review'),
    path('predict/', views.predict_chances, name='submit_prediction'),
]

ReviewPrediction/templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Iris prediction</title>
    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results">DB</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

ReviewPrediction/templates/login_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>OurApp</title>
    <link href="https://fonts.googleapis.com/css?family=Public+Sans:300,400,400i,700,700i&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <script defer src="https://use.fontawesome.com/releases/v5.5.0/js/all.js" integrity="sha384-GqVMZRt5Gn7tB9D9q7ONtcp4gtHIUEW/yG7h98J7IpE3kpi+srfFyyB/04OV6pG0" crossorigin="anonymous"></script>
    <link rel="stylesheet" type='text/css' href="{% static "main2.css" %}" />
  </head>
  <body>
    <header class="header-bar bg-primary mb-3">
      <div class="container d-flex flex-column flex-md-row align-items-center p-3">
        <h4 class="my-0 mr-md-auto font-weight-normal">
          <a href="/" class="text-white"> Restaurant Review Classification </a>
        </h4>
        <form class="mb-0 pt-2 pt-md-0" actiom="" method="POST" role="form">
          {% csrf_token %}
          <div class="row align-items-center">
            <div class="col-md mr-0 pr-md-0 mb-3 mb-md-0">{{form.username}}</div>
            <div class="col-md mr-0 pr-md-0 mb-3 mb-md-0">{{form.password}}</div>
            <div class="col-md-auto">
              <button class="btn btn-success btn-sm">Sign In</button>
            </div>
            <a href="{% url 'myapp:register_page' %}" class="text-white"> <i class="glyphicon glyphicon-plus-sign"></i>Register </a>
          </div>
        </form>
      </div>
    </header>

    <div class="container py-md-5">
      <img src="{% static 'images/img1.jpg' %}" alt="Snow" style="width: 100%; height: 350px" />
    </div>

    <footer class="border-top text-center small text-muted py-3">
      <p><a href="/" class="mx-1">Home</a> | <a class="mx-1" href="/about-us">About Us</a> | <a class="mx-1" href="/terms">Terms</a></p>
      <p class="m-0">Copyright &copy; 2022 <a href="/" class="text-muted">ReviewApp</a>. All rights reserved.</p>
    </footer>
  </body>
</html>

ReviewPrediction/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>OurApp</title>
    <link href="https://fonts.googleapis.com/css?family=Public+Sans:300,400,400i,700,700i&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <script defer src="https://use.fontawesome.com/releases/v5.5.0/js/all.js" integrity="sha384-GqVMZRt5Gn7tB9D9q7ONtcp4gtHIUEW/yG7h98J7IpE3kpi+srfFyyB/04OV6pG0" crossorigin="anonymous"></script>
    <link rel="stylesheet" type='text/css' href="{% static "main.css" %}" />
  </head>
  <body>
    <header class="header-bar bg-primary mb-3">
      <div class="container d-flex flex-column flex-md-row align-items-center p-3">
        <h4 class="my-0 mr-md-auto font-weight-normal">
          <a href="/" class="text-white"> Restaurant Review Classification </a>
        </h4>
        <a href="{% url 'myapp:login' %}" class="text-white"> <i class="glyphicon glyphicon-plus-sign"></i>Sign in </a>
      </div>
    </header>

    <div class="container py-md-2">
      <div class="row align-items-center">
        <div class="col-lg-7 py-3 py-md-5">
          <!-- text-muted-->
          <p class="lead">Are you sick of short tweets and impersonal &ldquo;shared&rdquo; posts that are reminiscent of the late 90&rsquo;s email forwards? We believe getting back to actually writing is the key to enjoying the internet again.</p>
        </div>
        <div class="col-lg-5 pl-lg-5 pb-3 py-lg-5">
          <form action="" method="POST" role="form">
            {% csrf_token %} {% for field in form %}
            <div>
              {% for error in field.errors %}
              <span class="errorlist" style="color: red"> {{error}} </span>
              {% endfor %}
            </div>
            {% endfor %}
            <div class="form-group">
              <label for="username-register" class="text-muted mb-1">
                <small>Username</small>
              </label>
              {{ form.username }}
            </div>
            <div class="form-group">
              <label for="email-register" class="text-muted mb-1">
                <small>Email</small>
              </label>
              {{ form.email }}
            </div>
            <div class="form-group">
              <label for="password-register" class="text-muted mb-1">
                <small>Password</small>
              </label>
              {{form.password1}}
            </div>
            <div class="form-group">
              <label for="password-register" class="text-muted mb-1">
                <small>Confirm Password</small>
              </label>
              {{form.password2}}
            </div>
            <button type="submit" class="py-3 mt-4 btn btn-lg btn-success btn-block">Sign up for ComplexApp</button>
          </form>
        </div>
      </div>
    </div>

    <footer class="border-top text-center small text-muted py-3">
      <p><a href="/" class="mx-1">Home</a> | <a class="mx-1" href="/about-us">About Us</a> | <a class="mx-1" href="/terms">Terms</a></p>
      <p class="m-0">Copyright &copy; 2022 <a href="/" class="text-muted">ReviewApp</a>. All rights reserved.</p>
    </footer>
  </body>
</html>

ReviewPrediction/templates/results.html
{% extends "base.html" %}

{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h1>Prediction Results</h1>

            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Sepal length</th>
                <th scope="col">Sepal width</th>
                <th scope="col">Petal length</th>
                <th scope="col">Petal width</th>
                <th scope="col">Prediction</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.sepal_length }}</td>
                    <td>{{ data.sepal_width }}</td>
                    <td>{{ data.petal_length }}</td>
                    <td>{{ data.petal_width }}</td>
                    <td>{{ data.classification }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

ReviewPrediction/templates/review.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant Feedback Form</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous" />
    <link rel="stylesheet" type='text/css' href="{% static "review.css" %}" />
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  </head>
  <body>
    <!-- Required popup view -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <h5>Prediction Input:</h5>
            <div>Restaurant Name : <span id="sl"></span></div>
            <div>Food Quality : <span id="sw"></span></div>
            <div>Speed of Delivery : <span id="pl"></span></div>
            <div>Price : <span id="pw"></span></div>
            <div>Feedback : <span id="tx"></span></div>
            <h5 class="pt-3">Prediction Classification:</h5>
            <div id="prediction"></div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <div class="testbox">
      <form id="post-form" action="" method="POST" role="form">
        {% csrf_token %}
        <a href="{% url 'myapp:logout' %}" style="float: right" class="text-black"> <i class="glyphicon glyphicon-plus-sign"></i>Logout </a>
        <h1>Restaurant Feedback Form</h1>
        <p>Please help us improve our restaurant services by filling in our feedback form. Thank you!</p>
        <h4>Restaurant Name</h4>
        <div class="name">{{form.name}}</div>
        <h4>Review</h4>
        <table>
          <tr>
            <td class="first-col">Food Quality</td>
            <td>{{form.food}}</td>
          </tr>
          <tr>
            <td class="first-col">Speed of Service</td>
            <td>{{form.speed}}</td>
          </tr>
          <tr>
            <td class="first-col">Price</td>
            <td>{{form.price}}</td>
          </tr>
        </table>
        <h4>Any comments, questions or suggestions?</h4>
        {{form.text}}
        <div class="btn-block">
          <button data-toggle="modal" data-target="#exampleModal" type="submit" href="/">Send Feedback</button>
        </div>
      </form>
    </div>
    <script>
      $(document).on("submit", "#post-form", function (e) {
        e.preventDefault()
        $.ajax({
          type: "POST",
          url: '{% url "myapp:submit_prediction" %}',
          data: {
            name: $("#name").val(),
            food: $("#food").val(),
            speed: $("#speed").val(),
            price: $("#price").val(),
            text: $("#text").val(),
            csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val(),
            action: "post",
          },
          success: function (json) {
            document.forms["post-form"].reset()
            document.getElementById("prediction").innerHTML = json["result"] // result
            document.getElementById("sl").innerHTML = json["name"]
            document.getElementById("sw").innerHTML = json["food"]
            document.getElementById("pl").innerHTML = json["speed"]
            document.getElementById("pw").innerHTML = json["price"]
            document.getElementById("tx").innerHTML = json["text"]
          },
          error: function (xhr, errmsg, err) {},
        })
      })
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>